server:
  context-path: /dealer

spring:
  datasource:
    url: jdbc:mysql://114.55.67.186:3306/bodyguard?useUnicode=true&characterEncoding=utf8
    username: root
    password: HZjiawawulian@163
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath:mapper/*.xml

SMS:
  url: http://210.5.152.195:1860/asmx/smsservice.aspx?
  name: 15267220111
  pwd: 2609597D636BF56286AFD41229F7
